RSSFeeds/Models/RSSFeed.cs
namespace RSSFeeds.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class RSSFeed
    {
        [MaxLength(50)]
        [Display(Name = "Feed Title")]
        public string RSSFeedTitle { get; set; }

        [Key, Column(Order = 0)]
        [MaxLength(255)]
        public string RSSFeedUrl { get; set; }

        public virtual ICollection<RSSFeedItem> RSSFeedItems { get; set; }

        [Key, Column(Order = 1)]
        public virtual int UserId { get; set; }
        public virtual UserProfile User { get; set; }
    }
}

RSSFeeds/Controllers/RssFeedController.cs
namespace RSSFeeds.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using RSSFeeds.Models;
    using RSSFeeds.Services.Repository;

    [Authorize]
    public class RssFeedController : Controller
    {
        public IRepository<RSSFeed> RSSFeedRepo { get; set; }
        public IRepository<UserProfile> UserProfileRepo { get; set; }

        public RssFeedController(IRepository<UserProfile> userProfileRepo, IRepository<RSSFeed> rssFeedRepo)
        {
            this.RSSFeedRepo = rssFeedRepo;
            this.UserProfileRepo = userProfileRepo;
        }

        [HttpGet]
        public ViewResult AddNewRssFeed()
        {
            return this.View();
        }
     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddNewRssFeed(RSSFeed rssFeed)
        {
            if(!ModelState.IsValid)
                return this.View(rssFeed);

            rssFeed.User = UserProfileRepo.Get(u => u.UserName == User.Identity.Name).FirstOrDefault();
            RSSFeedRepo.Add(rssFeed);
            RSSFeedRepo.CommitChanges();
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            var user = UserProfileRepo.Get(up => up.UserName == User.Identity.Name).FirstOrDefault();
            if (user == null) 
                return new RedirectResult("~/Account/Login");

            var rssFeeds = user.Feeds.ToList();
            return this.View(rssFeeds);
        }

        public ActionResult DeleteFeed(string rssFeedUrl)
        {
            RSSFeedRepo.Remove(RSSFeedRepo.Get(feed => feed.RSSFeedUrl == rssFeedUrl && feed.User.UserName == User.Identity.Name));
            RSSFeedRepo.CommitChanges();
            return RedirectToAction("List");
        }

        public ActionResult NavigateToRSSFeedItems(RSSFeed firstRssFeed)
        {
            return RedirectToAction("List", "RSSFeedItems", new { rssFeedUrl = firstRssFeed.RSSFeedUrl });
        }

        [HttpGet]
        public ActionResult EditFeed(string rssFeedUrl)
        {
            var rssFeed = RSSFeedRepo.Get(f => f.RSSFeedUrl == rssFeedUrl && f.User.UserName == User.Identity.Name).FirstOrDefault();
            return View(rssFeed);
        }

        [HttpPost]
        public ActionResult EditFeed(RSSFeed rssFeed)
        {
            RSSFeedRepo.Update(rssFeed, rssFeed.RSSFeedUrl, rssFeed.UserId);
            RSSFeedRepo.CommitChanges();
            return RedirectToAction("List");
        }
    }
}

RSSFeeds/Controllers/RssFeedItemsController.cs
namespace RSSFeeds.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using RSSFeeds.Helpers;
    using RSSFeeds.Models;
    using RSSFeeds.Services.Repository;

    public class RssFeedItemsController : Controller
    {
        private UserProfile UserProfile {
            get
            {
                return UserProfileRepository.Get(user => user.UserName == User.Identity.Name).FirstOrDefault();
            }
        }
        public IRepository<RSSFeed> RSSFeedRepository { get; set; }
        public IRepository<RSSFeedItem> RSSFeedItemRepository { get; set; }
        public IRepository<UserProfile> UserProfileRepository { get; set; }

        public RssFeedItemsController(IRepository<UserProfile> userProfileRepository, IRepository<RSSFeed> rssFeedRepository, IRepository<RSSFeedItem> rssFeedItemRepository)
        {
            RSSFeedRepository = rssFeedRepository;
            RSSFeedItemRepository = rssFeedItemRepository;
            UserProfileRepository = userProfileRepository;
        }

        public ViewResult List(string rssFeedUrl)
        {
            var rssFeed = this.UserProfile.Feeds.FirstOrDefault(f => f.RSSFeedUrl == rssFeedUrl);
            if (rssFeed == null)
                throw new Exception("The specified RSS feed could not be found");

            var rssFeedItems = RSSFeedItemHelper.GetRSSFeedItems(rssFeed, UserProfile).ToList();
            var itemsNotInRepo = rssFeedItems.Except(rssFeed.RSSFeedItems, new RSSFeedItemComparer());
            if (itemsNotInRepo.Any())
            {
                RSSFeedItemRepository.Add(itemsNotInRepo);
                RSSFeedItemRepository.CommitChanges();
            }

            var feedItems = rssFeed.RSSFeedItems;
            return View(feedItems);
        }

        [HttpGet]
        public ActionResult Detail(string rssFeedUrl, string rssFeedItemId)
        {
            var feed = (from f in UserProfile.Feeds
                       where f.RSSFeedUrl == rssFeedUrl
                        select f.RSSFeedItems.FirstOrDefault(fi => fi.RSSFeedItemId == rssFeedItemId)).FirstOrDefault();
            if (feed == null)
                throw new Exception("The specified RSS Feed Item could not be found");
            if (!feed.Read)
            {
                feed.Read = true;
                RSSFeedItemRepository.Update(feed, feed.RSSFeedItemId, feed.Title);
            }
            return this.View(feed);
        }

        public ActionResult UpdateFeedReadStatus(string rssFeedItemId, string rssFeedUrl, bool read)
        {
            var feed = (from f in UserProfile.Feeds
                       where f.RSSFeedUrl == rssFeedUrl
                       select f.RSSFeedItems.FirstOrDefault(fi => fi.RSSFeedItemId == rssFeedItemId)).FirstOrDefault();
            if (feed == null)
                throw new Exception("The specified RSS Feed Item could not be found");

            feed.Read = read;
            this.RSSFeedItemRepository.Update(feed, feed.RSSFeedItemId, feed.Title);

            return RedirectToAction("List", "RSSFeedItems", new { rssFeedUrl = feed.RSSFeedUrl });
        }
    }
}

RSSFeeds/Views/RssFeed/AddNewRssFeed.cshtml
@model RSSFeeds.Models.RSSFeed
@{
    ViewBag.Title = "Add a new RSS Feed to the Feed List";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>@ViewBag.Title</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.RSSFeedTitle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RSSFeedTitle)
            @Html.ValidationMessageFor(model => model.RSSFeedTitle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RSSFeedUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RSSFeedUrl)
            @Html.ValidationMessageFor(model => model.RSSFeedUrl)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    <b>
        @Html.ActionLink("Back to Feed List", "List")
    </b>
</div>

RSSFeeds/Views/RssFeed/EditFeed.cshtml
@model RSSFeeds.Models.RSSFeed

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>RSSFeed</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.RSSFeedTitle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RSSFeedTitle)
            @Html.ValidationMessageFor(model => model.RSSFeedTitle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RSSFeedUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RSSFeedUrl)
            @Html.ValidationMessageFor(model => model.RSSFeedUrl)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    <b>
        @Html.ActionLink("Back to Feed List", "List")
    </b>
</div>

RSSFeeds/Views/RssFeed/List.cshtml
@model IEnumerable<RSSFeeds.Models.RSSFeed>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RSSFeedTitle)
        </th>
        <th></th>
    </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.ActionLink(item.RSSFeedTitle, "List", "RssFeedItems", new { rssFeedUrl = item.RSSFeedUrl }, null)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditFeed", new { rssFeedUrl = item.RSSFeedUrl }) |
                @Html.ActionLink("Delete", "DeleteFeed", new { rssFeedUrl = item.RSSFeedUrl })
            </td>
        </tr>
    }
</table>


<p>
    <b>
        @Html.ActionLink("Add a feed to the list", "AddNewRssFeed")
    </b>
</p>